### ISSUE TITLE
Issue on page /functions/classes.html - Advanced Tip on Special Class Methods

### ISSUE THREAD

**Issue by AEgbert** [cburdine/materials-ml-workshop#10]
In the Advanced Tip on Special Class Methods on the Classes and Object-Oriented Programming page, the description for `__repr__()` mentions that it is called by `print()` to produce the string representation of the object. This is not entirely correct, in a subtle way.

`print()` actually calls `__str__()` to produce the human-readable string representation of the object. If no custom `__str__()` implementation is provided by the class, the default implementation merely returns the result of `__repr__()`. The goal of `__repr__()` is to return a valid python expression that can be used to recreate the object (if possible).

In the context of introducing beginners to Python, it may be more advisable to teach them about `__str__()` instead of `__repr__()`.

More info on `__repr__()` and `__str__()` is available [here](https://docs.python.org/3/reference/datamodel.html?highlight=repr#object.__repr__).

**Comment by cburdine** [comment]
A good point. I'll change it to __str__. 
My original though process for using __repr__ as the example is that the "official" (programmer-end) string representation should be implemented first and the "unofficial" (user-end) string representation second, if at all. That said, I think you are right in that __str__ is easier for beginners to understand.
