### ISSUE TITLE
Issue on page /data_types/sets_and_dicts.html

### ISSUE THREAD

**Issue by AdamGoat** [cburdine/materials-ml-workshop#9]
The example John von Neumann dictionary should read:

person = {
    'name' : 'John von Neumann',
    'age' : 53,
    'occupation' : 'Mathematician',
    'birthday' : ('December ', 28, 1903)
}

To have correct birthday and age at death.

**Comment by cburdine** [comment]
This issue should be resolved now. Thanks for opening it!
